language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Before Install
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_script:
  - ls

script:
  - "./gradlew clean build"

before deploy:
  - ls
  - zip -r SpringBoot200-Web *
  - mkdir -p deploy
  - mv SpringBoot200-Web.zip deploy/SpringBoot200-Web.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot200-web # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: JungHa-Cho/SpringBoot200-Web  #Github 주소
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  slack: nanoit-ops:QjtkUksaOt6kgsylbK1VQBls
  email:
    recipients:
      - cjh8487@naver.com